# Fundamentals of Statistics

## Unit 8

### Homework 10

In [3]:
import numpy as np

X = np.array([[1,1,1],[1,2,4],[1,3,9],[1,4,16],[1,5,25],[1,6,36],[1,7,49],[1,8,64],[1,9,81],[1,10,100]])
XT = X.transpose()

XT

array([[  1,   1,   1,   1,   1,   1,   1,   1,   1,   1],
       [  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [  1,   4,   9,  16,  25,  36,  49,  64,  81, 100]])

In [5]:
X

array([[  1,   1,   1],
       [  1,   2,   4],
       [  1,   3,   9],
       [  1,   4,  16],
       [  1,   5,  25],
       [  1,   6,  36],
       [  1,   7,  49],
       [  1,   8,  64],
       [  1,   9,  81],
       [  1,  10, 100]])

In [9]:
XTX = XT.dot(X)  
print(XTX)

[[   10    55   385]
 [   55   385  3025]
 [  385  3025 25333]]


In [19]:
XTX_INV=np.linalg.inv(XTX)

XTX_INV

array([[ 1.38333333, -0.525     ,  0.04166667],
       [-0.525     ,  0.24128788, -0.02083333],
       [ 0.04166667, -0.02083333,  0.00189394]])

In [22]:
Y = np.array([1,3,5,8,11,14,18,21,25,28])
Y = Y.transpose()
Y

array([ 1,  3,  5,  8, 11, 14, 18, 21, 25, 28])

In [23]:
XTY = XT.dot(Y)  
print(XTY)

[ 134  992 8016]


In [24]:
beta_hat=XTX_INV.dot(XTY)
beta_hat

array([-1.43333333,  2.00757576,  0.09848485])

## Unit 9

### Preparation Exercises for Principal Component Analysis

__The Empirical Average for a Data Set of Vectors__

In [24]:
import numpy as np 

x1 = [[8], [4], [7]]  
x2 = [[2], [8], [1]]
x3 = [[3], [1], [1]]
x4 = [[9], [7], [4]]

vctr1 = np.array(x1) 
vctr2 = np.array(x2) 
vctr3 = np.array(x3) 
vctr4 = np.array(x4) 

#calculating the empirical average
x_bar = 1/4*(vctr1 + vctr2 + vctr3 + vctr4)

In [25]:
print("The empirical average X_bar is:")
print(x_bar)

The empirical average X_bar is:
[[5.5 ]
 [5.  ]
 [3.25]]


__The Empirical Covariance for a Data Set of Vectors__

In [8]:
import numpy as np 

x1 = [[8], [4], [7]]  
x2 = [[2], [8], [1]]
x3 = [[3], [1], [1]]
x4 = [[9], [7], [4]]

v1 = np.array(x1) 
v2 = np.array(x2) 
v3 = np.array(x3) 
v4 = np.array(x4) 

# transpose vectors
vt1 = v1.transpose()
vt2 = v2.transpose()
vt3 = v3.transpose()
vt4 = v4.transpose()

# calculating the empirical average
x_bar = 1/4*(v1 + v2 + v3 + v4)

# empirical average transpose
x_bar_t = x_bar.transpose()

In [11]:
# covariance

s = 1/4*((v1*vt1)+(v2*vt2)+(v3*vt3)+(v4*vt4))-(x_bar*x_bar_t)

In [12]:
s

array([[9.25  , 1.    , 6.375 ],
       [1.    , 7.5   , 0.    ],
       [6.375 , 0.    , 6.1875]])

### An Orthogonal Projection Matrix I

https://learning.edx.org/course/course-v1:MITx+18.6501x+2T2022/block-v1:MITx+18.6501x+2T2022+type@sequential+block@u9s1_PCA/block-v1:MITx+18.6501x+2T2022+type@vertical+block@u9s1_PCA-tab5

In [9]:
import numpy as np

# this is a different approach to calculate the covariance
x1=np.matrix([8,4,7])
x2=np.matrix([2,8,1])
x3=np.matrix([3,1,1])
x4=np.matrix([9,7,4])

xbar=(x1+x2+x3+x4)*(1/4)
print("Xbar",xbar)

covar=((1/4)*((x1.T@x1) + (x2.T@x2) + (x3.T@x3) + (x4.T@x4))) - (xbar.T@xbar)




H=np.identity(3) - ((1/3) * np.ones((3,3)))

print("H",H)

v=np.matrix([2,-1,-2])

Hv = H@v.T

print("Hv",Hv)

Xbar [[5.5  5.   3.25]]
H [[ 0.66666667 -0.33333333 -0.33333333]
 [-0.33333333  0.66666667 -0.33333333]
 [-0.33333333 -0.33333333  0.66666667]]
Hv [[ 2.33333333]
 [-0.66666667]
 [-1.66666667]]


### 6. Measuring the Spread of a Point Cloud

https://learning.edx.org/course/course-v1:MITx+18.6501x+2T2022/block-v1:MITx+18.6501x+2T2022+type@sequential+block@u9s1_PCA/block-v1:MITx+18.6501x+2T2022+type@vertical+block@u9s1_PCA-tab6

In [16]:
import numpy as np
import math

x1=np.matrix([1,2])  #vector x1
x2=np.matrix([3,4])  #vector x3
x3=np.matrix([-1,0]) #vector x3


In [17]:
u=np.matrix([1/np.sqrt(5),2/np.sqrt(5)]) #vector u
u

matrix([[0.4472136 , 0.89442719]])

In [18]:
# Task: Project vector u on vector v
  
# Apply the formula as mentioned above
# for projecting a vector onto another vector
# find dot product using np.dot()
proj_of_u_on_x1 = (u@x1.T)*u
proj_of_u_on_x2 = (u@x2.T)*u
proj_of_u_on_x3 = (u@x3.T)*u
  
print("Projection of Vector u on Vector x1 is: ", proj_of_u_on_x1)
print("Projection of Vector u on Vector x2 is: ", proj_of_u_on_x2)
print("Projection of Vector u on Vector x3 is: ", proj_of_u_on_x3)

Projection of Vector u on Vector x1 is:  [[1. 2.]]
Projection of Vector u on Vector x2 is:  [[2.2 4.4]]
Projection of Vector u on Vector x3 is:  [[-0.2 -0.4]]
