# Fundamentals of Statistics

## Unit 8

### Homework 10

In [3]:
import numpy as np

X = np.array([[1,1,1],[1,2,4],[1,3,9],[1,4,16],[1,5,25],[1,6,36],[1,7,49],[1,8,64],[1,9,81],[1,10,100]])
XT = X.transpose()

XT

array([[  1,   1,   1,   1,   1,   1,   1,   1,   1,   1],
       [  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [  1,   4,   9,  16,  25,  36,  49,  64,  81, 100]])

In [5]:
X

array([[  1,   1,   1],
       [  1,   2,   4],
       [  1,   3,   9],
       [  1,   4,  16],
       [  1,   5,  25],
       [  1,   6,  36],
       [  1,   7,  49],
       [  1,   8,  64],
       [  1,   9,  81],
       [  1,  10, 100]])

In [9]:
XTX = XT.dot(X)  
print(XTX)

[[   10    55   385]
 [   55   385  3025]
 [  385  3025 25333]]


In [19]:
XTX_INV=np.linalg.inv(XTX)

XTX_INV

array([[ 1.38333333, -0.525     ,  0.04166667],
       [-0.525     ,  0.24128788, -0.02083333],
       [ 0.04166667, -0.02083333,  0.00189394]])

In [22]:
Y = np.array([1,3,5,8,11,14,18,21,25,28])
Y = Y.transpose()
Y

array([ 1,  3,  5,  8, 11, 14, 18, 21, 25, 28])

In [23]:
XTY = XT.dot(Y)  
print(XTY)

[ 134  992 8016]


In [24]:
beta_hat=XTX_INV.dot(XTY)
beta_hat

array([-1.43333333,  2.00757576,  0.09848485])

## Unit 9

### Preparation Exercises for Principal Component Analysis

__The Empirical Average for a Data Set of Vectors__

In [22]:
import numpy as np 

x1 = [[8], [4], [7]]  
x2 = [[2], [8], [1]]
x3 = [[3], [1], [1]]
x4 = [[9], [7], [4]]

vctr1 = np.array(x1) 
vctr2 = np.array(x2) 
vctr3 = np.array(x3) 
vctr4 = np.array(x4) 

#calculating the empirical average
x_bar = 1/4*(vctr1 + vctr2 + vctr3 + vctr4)

In [23]:
print("The empirical average X_bar is:")
print(x_bar)

The empirical average X_bar is:
[[5.5 ]
 [5.  ]
 [3.25]]
